# Generated by Django 6.0.3 on 2026-03-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration", models.IntegerField()),
                ("genre", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("poster_url", models.URLField()),
                ("trailer_url", models.URLField()),
                ("film_url", models.URLField()),
            ],
        ),
    ]
