# Generated by Django 6.0.3 on 2026-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["id"],
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="subscriptions",
            field=models.ManyToManyField(to="subscription.subscription"),
        ),
    ]
