# Generated by Django 6.0.3 on 2026-03-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genre", "0001_initial"),
        ("movie", "0002_alter_movie_options_movie_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="genre.genre",
            ),
        ),
    ]
